### ISSUE TITLE
F1 still not available on DS923+

### ISSUE THREAD

**Issue by ramteid** [007revad/Synology_SHR_switch#30]
I've got a Synology DS923+. I was hoping to use your script to enable F1 for my all-SSD configuration. Unfortunately it doesn't seem to work.

I ran the script and switched my NAS to `Raid Group` mode:

![image](https://github.com/007revad/Synology_SHR_switch/assets/710061/734b23e7-c8a7-430a-aa21-2eff24435556)

Afterwards I rebooted the NAS. 
When creating a new storage pool, I still don't have `F1` as an option:

![image](https://github.com/007revad/Synology_SHR_switch/assets/710061/1de7568f-7cc1-43ab-b1c3-dc979b3cd010)

It seems, F1 is just not implemented on the DS923+ :-(

**Comment by 007revad** [comment]
Unfortunately the script can't enable RAID F1 on models that don't have RAID F1 built in.

**Comment by ramteid** [comment]
That's what I suspected. Thank you though.
