### ISSUE TITLE
SHR (not an issue)

### ISSUE THREAD

**Issue by jjvelar** [007revad/Synology_SHR_switch#51]
Hi @007revad,

Thanks for providing these scripts. Much appreciated.

I am currently using a RAID1 configuration but plan to add additional drives so your script allows me to consider migrating to RAID5 or SHR.

How dows this work? I mean, I am not an expert user but Synology does not allow to move from RAID to SHR, so was wondering which kind of sorcery :-) are you using, and which will be the process.

Thanks in advance for your help and support.

**Comment by 007revad** [comment]
The script doesn't allow changing an existing RAID 5 storage pool to SHR, or vice versa. It only enables the option to create an SHR storage pool on enterprise models that don't have SHR.

**Comment by jjvelar** [comment]
Oh, I see.
Thanks for clarifying.
